version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: lzhang2
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    # volumes:
    #   - /goinfre/lzhang2/pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lzhang2@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - "8080:80"
    depends_on:
      - db
# 实现 数据持久化，让你重启 Docker 或电脑时数据库不会丢失
volumes:
  pgdata:

# docker exec -it ex02-db-1 psql -U lzhang2 -d piscineds
# 没有psql -U lzhang2 -d piscineds -h localhost -W

# \l              -- 查看数据库列表
# \c dbname	连接到数据库
# \c piscineds    -- 连接数据库（你已经在里面了）
# \dt             -- 查看数据表（如果还没建会为空）
# DROP TABLE students; -- 删除数据
# \d table_name	查看某个表的结构（字段、类型、约束等）
# \dn	显示所有 schema
# \df	列出函数（functions）
# \dv	列出视图（views）
# \q	退出 psql
# \?	查看 psql 所有命令帮助
# \h	查看 SQL 指令帮助，如 \h SELECT
# \timing	显示每个 SQL 语句执行时间（用于调试性能）

# 数据操作辅助
# 命令	作用
# \x	切换扩展显示模式（对长数据很有用）
# SELECT * FROM table_name LIMIT 10;	快速查看表中前10条数据
# TRUNCATE table_name;	清空表但不删除结构
# DROP TABLE table_name;	删除整个表结构和数据
# ALTER TABLE ... RENAME TO ...	修改表名